load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library", "go_test")

go_library(
    name = "go_default_library",
    srcs = [
        "backlight.go",
    ],
    deps = [
        "//sbpgo:go_default_library",
    ],
    visibility = ["//visibility:public"],
)
