#!/bin/sh

text=$(/usr/share/i3blocks/battery)

# Strip out the DIS and CHR indicators. Use a color instead.
nodis=$(echo "$text" | sed 's/ DIS//')
nochr=$(echo "$nodis" | sed 's/ CHR//')

# The default (white) is shown when the battery is fully charged.
color='#FFFFFF'
if [ "$text" != "$nodis" ]; then
  # DIS was removed. Use yellow to indicate discharge.
  color='#FFFF00'
elif [ "$nodis" != "$nochr" ]; then
  # CHR was removed. Use blue to indicate charging.
  color='#0077FF'
fi

echo "$nochr" | i3blocks-recolor --fg="$color"
