#!/bin/sh

# Fetch fresh calendar information every minute.
FETCH_INTERVAL=60

DIR="${HOME}/.i3cal"
LAST_FILE="${DIR}/desktime.last"
LAST_TIMESTAMP_FILE="${DIR}/desktime.last.timestamp"

now="$(date +%s)"
last_timestamp="$(cat "$LAST_TIMESTAMP_FILE")"
elapsed="$((now - last_timestamp))"

if (( elapsed >= FETCH_INTERVAL )); then
  # Fetch new results from Calendar.
  if ! desktime > "$LAST_FILE"; then
    echo ERR
    exit 1
  fi
  echo "$now" > "$LAST_TIMESTAMP_FILE"
fi
seconds="$(cat "$LAST_FILE")"

if [ -z "$seconds" ]; then
  # No upcoming events, so don't print anything.
  exit
fi

# Pretty-print the remaining seconds, using exactly 3 characters.
minutes="$((seconds / 60))"
if (( minutes < 0 )); then
  minutes=0
fi
if (( minutes <= 9 )); then
  echo " ${minutes}m"
  exit
fi
if (( minutes <= 99 )); then
  echo "${minutes}m"
  exit
fi

hours="$((minutes / 60))"
if (( hours <= 9 )); then
  echo " ${hours}h"
  exit
fi
if (( hours <= 99 )); then
  echo "${hours}h"
  exit
fi
# It's more than 99 hours in the future? Thats, like, forever!
echo "inf"

