#!/bin/sh
#
# Blocklet which displays the number of minutes or "desk time" I have left,
# i.e. the number of minutes until my next meeting.

if ! which desktime >/dev/null; then
  # Disable this blocklet on machines with no Calendar access.
  exit
fi

# Fetch fresh calendar information every minute.
FETCH_INTERVAL=60

DIR="${HOME}/.i3cal"
LAST_FILE="${DIR}/desktime.last"
LAST_TIMESTAMP_FILE="${DIR}/desktime.last.timestamp"

now="$(date +%s)"
last_timestamp="$(cat "$LAST_TIMESTAMP_FILE")"
elapsed="$((now - last_timestamp))"

if (( elapsed >= FETCH_INTERVAL )); then
  # Fetch new results from Calendar.
  if ! desktime > "$LAST_FILE"; then
    echo "<span color='#FFFF00' bgcolor='#000000'> 📅 ERR </span>"
    exit
  fi
  echo "$now" > "$LAST_TIMESTAMP_FILE"
fi
seconds="$(cat "$LAST_FILE")"

if [ -z "$seconds" ]; then
  # No upcoming events, so don't print anything.
  exit
fi

# Pretty-print the remaining seconds, using exactly 3 characters.
text="📅"
if (( seconds < 60 )); then
  text="$text now"
else
  minutes="$(( seconds / 60 ))"
  if (( minutes <= 9 )); then
    text="$text  ${minutes}m"
  elif (( minutes <= 99 )); then
    text="$text ${minutes}m"
  else
    # Round to the nearest hour.
    hours="$(( (minutes + 30) / 60 ))"
    if (( hours <= 9 )); then
      text="$text  ${hours}h"
    elif (( hours <= 99 )); then
      text="$text ${hours}h"
    else
      # It's more than 99 hours in the future? Thats, like, forever! Don't print
      # anything
      exit
    fi
  fi
fi

# Foreground is always yellow.
fgcolor="#FFFF00"

# Background is usually black, but turns bright red when it's time to go.
bgcolor="#000000"
if (( seconds <= 90 )); then
  bgcolor="#FF0000"
fi

echo "<span color='${fgcolor}' bgcolor='${bgcolor}'> ${text} </span>"
