#!/bin/sh

iface=$(get-iface)

if [ -z "$iface" ]; then
  # No network access.
  echo -ne " X\n X\n#FF0000\n#000000\n"
  exit
fi

iface=$(echo "$iface" | cut -c 1 | tr a-z A-Z)
echo -ne " ${iface}\n ${iface}\n#00FF00\n#000000\n"
