#!/bin/bash
#
# My own blocklet for the network interface. Includes an indicator (W/E/X) for
# wifi/wired/down along with a wifi strength percentage.
#
# TODO: reimplement in fish

iface=$(get-iface)

if [ -z "$iface" ]; then
  # No network access.
  echo -ne "down\ndown\n#FF0000\n#000000\n"
  exit
fi

firstLetter="$(echo $iface | cut -c 1)"
if [ "$firstLetter" == "w" ]; then
  # Ripped off from /usr/share/i3blocks/wifi.
  quality="$(grep "$iface" /proc/net/wireless | awk '{ print int($3 * 100 / 70) }')%"
  quality=$(echo "$quality" | sbpgo_main format_percent)
  text="$(iwgetid -r)${quality}"
elif [ "$firstLetter" == "e" ]; then
  text="eth "
else
  text="$iface "
fi

text="${text}$(sbpgo_main network_usage --iface=$iface --network_usage_history_id=bar)"

echo -ne "${text}\n${text}\n#00FF00\n#000000\n"
