#!/bin/bash
#
# My own blocklet for the network interface. Includes an indicator (W/E/X) for
# wifi/wired/down along with a wifi strength percentage.

# TODO: rename this to "network"

iface=$(get-iface)

if [ -z "$iface" ]; then
  # No network access.
  echo -ne "down\ndown\n#FF0000\n#000000\n"
  exit
fi

text="$iface "
if [ "$(echo $iface | cut -c 1)" == "w" ]; then
  # Ripped off from /usr/share/i3blocks/wifi.
  quality="$(grep "$iface" /proc/net/wireless | awk '{ print int($3 * 100 / 70) }')%"
  quality=$(echo "$quality" | format-percent)
  text="$(iwgetid -r)${quality}"
fi

text="${text}$(i3bar-netusage --iface=$iface --history_id=bar)"

echo -ne "${text}\n${text}\n#00FF00\n#000000\n"
