#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Pads i3blocks status entries with spaces as necessary.

import sys

LEFT_BAR  = u'▏'
RIGHT_BAR = u'▕'


def padLine(line):
  if not line.startswith(RIGHT_BAR):
    line = ' ' + line
  if not line.endswith(LEFT_BAR):
    line = line + ' '
  return line


if __name__ == '__main__':
  text = sys.stdin.read()
  text = unicode(text, 'utf-8')

  lines = text.splitlines()
  for i in range(len(lines)):
    # Only pad the first 2 lines, since they contain the display text.
    if i < 2:
      lines[i] = padLine(lines[i])
  text = '\n'.join(lines)

  text = text.encode('utf-8')
  sys.stdout.write(text)
