#!/bin/sh
# Adds a new mode to Xrandr and registers it with a particular output. Usage:
#   add-x-mode width height output

width="$1"
height="$2"
output="$3"

if [ -z "$width" ]; then
  echo "Width not specified"
  exit 1
fi
if [ -z "$height" ]; then
  echo "Height not specified"
  exit 1
fi
if [ -z "$output" ]; then
  echo "Output not specified"
  exit 1
fi

# Use cut to remove the "Modeline:" prefix. Also remove the quotation marks
# around the mode name.
mode_line="$(cvt "$width" "$height" | grep Modeline | \
             cut --delim=" " --fields=2- | tr --delete "\"")"

# Remove the mode name so we can process it separately.
mode_name="$(echo "$mode_line" | cut --delim=" " --fields=1)"
mode_line="$(echo "$mode_line" | cut --delim=" " --fields=2-)"

# Remove the _60.00 suffix from the mode name.
mode_name="$(echo "$mode_name" | cut --delim="_" --fields=1)"

echo "Adding mode ${mode_name}:"
echo "$mode_line"

# Register the new mode. This may fail if the mode already exists; ignore that
# failure.
xrandr --newmode "$mode_name" $mode_line

echo "Registering mode $mode_name with output $output"
xrandr --addmode "$output" "$mode_name"

echo "Success"
