#!/bin/sh
# Sets the desktop background image using feh.
# Suppress stdout and stderr; feh often complains if it is run before X starts
# up. We don't want to get email spam from cron in this case.
export DISPLAY=:0.0
feh --no-fehbg --bg-fill \
  $HOME/sbp-linux-config/bin/wallpaper/swiss_night_sky.jpg \
  1>/dev/null 2>/dev/null
