#!/bin/sh
# Spawns a job and disowns it. Useful for starting GUI applications from a
# terminal.

# Redirect all output to the sink so that we don't see any polluting our
# terminal.
nohup "$@" &> /dev/null &
