#!/usr/bin/env python
# Script for handling i3 workspaces with custom, user-entered names. The
# following arguments are accepted:
#    One of:
#      focus - focuses the chosen workspace (default)
#      move - moves focused container to the chosen workspace and focuses it.
#      rename - renames the current workspace.
#  AND
#    One of:
#      menu - pre-populate the dmenu with the names of all existing
#          workspaces (default).
#      freeform - Don't pre-populate dmenu with anything--allow fully
#          custom input lines.
#      auto - Don't use a dmenu at all; instead, pick the next available
#          numeric name.

import sys
import string
import subprocess
import json

# Process arguments.
action = 'focus'
namePicker = 'menu'
for arg in sys.argv[1:]:
  if arg in ['focus', 'move', 'rename']:
    action = arg
  elif arg in ['menu', 'freeform', 'auto']:
    namePicker = arg
  else:
    raise KeyError

# Get a list of current workspaces, if that's going to be necessary.
if namePicker == 'menu' or namePicker == 'auto':
  workspaces = json.loads(
      subprocess.check_output(['i3-msg', '-t', 'get_workspaces']))
else:
  workspaces = []

def parseNumber(workspaceName):
  """ Tries to parse the workspace number out of a full workspace name. Returns
  -1 iff no number can be found.
  """
  split = string.split(workspaceName, ':', 1)
  try:
    # Use split[0] regardless of whether there is a split[1].
    return int(split[0])
  except ValueError:
    return -1

# Fetch names used by workspaces.
workspaceNames = []
focusedWorkspaceName = None
for w in workspaces:
  workspaceName = w['name']
  if w['focused']:
    focusedWorkspaceName = workspaceName
  workspaceNames.append(workspaceName)

# Use this map to look up a good dmenu caption for each action.
captions = {
  'move': 'Move to workspace:',
  'focus': 'Switch to workspace:',
  'rename': 'New workspace name:',
}

# Compute the workspace name.
if namePicker == 'menu' or namePicker == 'freeform':
  # Use dmenu.
  selection, _ = (subprocess.Popen(['dmenu', '-p', captions[action]],
      stdin= subprocess.PIPE, stdout= subprocess.PIPE)
      .communicate('\n'.join(workspaceNames)))
  selection = selection.strip()
  
  # If the user didn't add a numeric prefix, add one for them, keeping the
  # same workspace number.
  focusedWorkspaceNumber = parseNumber(focusedWorkspaceName)
  if focusedWorkspaceNumber > 0 and parseNumber(selection) < 0:
    selection = "%d:%s" % (focusedWorkspaceNumber, selection)
  
elif namePicker == 'auto':
  # Don't use dmenu; just compute the next available numeric name.
  selection = 1
  workspaceNumbers = set(map(parseNumber, workspaceNames))
  while selection in workspaceNumbers:
    selection += 1
  selection = str(selection)

if selection:
  # Use this map to look up the proper command format string for each action.
  i3Commands = {
    'move': 'move container to workspace "%(selection)s"; ' +
        'workspace "%(selection)s"',
    'focus': 'workspace "%(selection)s"',
    'rename': 'rename workspace to "%(selection)s"',
  }

  # Construct a command to send to i3.
  i3Command = i3Commands[action] % {'selection': selection}
    
  # Send the command. Suppress stdout, since i3-msg is kinda chatty.
  subprocess.call(['i3-msg', i3Command], stdout=subprocess.PIPE)
