#!/bin/sh
# Standard locking procedure. Instead of using the real i3lock, I use
# gnome-screensaver. Note that the screensaver instance is already running
# as a part of gnome-settings-daemon; this script just sends that instance
# a command.

gnome-screensaver-command --lock
