#!/bin/sh
# We could use "sudo shutdown -r now", but that requires the user to type
# their password. Instead, we can just rely on GNOME to handle this with
# a dialog.

/usr/lib/indicator-session/gtk-logout-helper --restart
