#!/bin/sh
# Suspend and lock screen. This uses the standard GNOME method, which does not
# require root privileges.

dbus-send --system --print-reply \
    --dest="org.freedesktop.UPower" \
    /org/freedesktop/UPower \
    org.freedesktop.UPower.Suspend
