#!/bin/sh
# Usage:   read-cache key
# Reads from the local memcached daemon. Prints out the value.

# tail --lines=+2 discards the first line (VALUE...).
# head --bytes=-7 discards the last END and pair of CRLFs.
echo -ne "get ${1}\r\nquit\r\n" \
    | nc localhost 11211 \
    | tail --lines=+2 \
    | head --bytes=-7
