#!/bin/sh
# Uses tmux to manage interaction with a long-running irssi process. First 
# checks if there is a tmux session named "irssi". If there is, this script 
# attaches to it. Otherwise, it creates a new "vpn" session, attaches to 
# it, and runs irssi in it.

irssi_session_name='irssi'
if ! tmux attach-session -t "irssi_session_name" ; then
  tmux new-session -s "irssi_session_name" irssi
fi
