#!/bin/sh
# Opens a dmenu to get a duration from the user, and then opens a floating
# window which will set the urgent signal once that duration passes.

duration=$(cat /dev/null | dmenu -p 'Ring alarm bell after: ')
if [ -z "$duration" ]; then
  exit 1
fi

# After vsleep sounds the bell, keep the terminal open until someone closes
# it manually.
cmd="echo Alarm ; vsleep --bell $duration ; echo 'Ring!' ; sleep 9999d"

fk terminator --command="$cmd" --title="alarm (floating_enable)"
