#!/bin/sh
# Monitors ~/logs, deleting any files which grow too large to protect the disk
# from growing overfull.

echo "This script runs forever. You'll have to Ctrl+C to quit."

# Allow logs to be up to 50MB in length.
MAX_SIZE=$((50 * 1024 * 1024))
LOGS_ROOT="${HOME}/logs"
PERIOD=5m

echo "Monitoring ${LOGS_ROOT}. If a file grows larger than ${MAX_SIZE} bytes,"
echo "I'm gonna delete it!"

while true; do
  for file in "${LOGS_ROOT}"/*; do
    file_size=$(stat -c%s "$file")
    if [[ $file_size -gt $MAX_SIZE ]]; then
      rm $file
      echo "Deleted $file"
    fi
  done

  # Throttle.
  sleep $PERIOD
done

