#!/bin/sh
# Script to unmount an external hard drive. This script assumes that the
# drive is /dev/sdb1. This script takes one command-line argument: the name
# to use for mounting the drive under /media.

if [ $# -lt 1 ]; then
  echo "Please supply the name used for mounting under /media."
  exit 1
fi

MOUNT_POINT=/media/$1
if [ ! -d "$MOUNT_POINT" ]; then
  echo "$MOUNT_POINT does not exist."
  exit 3
fi

sudo umount /dev/sdb1
sudo rmdir $MOUNT_POINT
