#!/bin/sh
#
# Sets up my MATE desktop settings.

gsettings set org.mate.interface monospace-font-name "Ubuntu Mono 15"

# Low sensitivity so it's easy to make fine adjustments.
gsettings set org.mate.peripherals-mouse motion-threshold 3
# High acceleration so the mouse moves quickly to the other side of the screen.
gsettings set org.mate.peripherals-mouse motion-acceleration 10

gsettings set org.mate.peripherals-touchpad motion-threshold 3
gsettings set org.mate.peripherals-touchpad motion-acceleration 7
gsettings set org.mate.peripherals-touchpad tap-to-click true
gsettings set org.mate.peripherals-touchpad vertical-two-finger-scrolling true
gsettings set org.mate.peripherals-touchpad horizontal-two-finger-scrolling true

# Pluma (text editor)
gsettings set org.mate.pluma side-pane-visible true
gsettings set org.mate.pluma wrap-mode GTK_WRAP_WORD
gsettings set org.mate.pluma color-scheme cobalt
gsettings set org.mate.pluma use-default-font true
gsettings set org.mate.pluma auto-save false
gsettings set org.mate.pluma bracket-matching true
gsettings set org.mate.pluma display-line-numbers true
gsettings set org.mate.pluma tabs-size 2
gsettings set org.mate.pluma right-margin-position 80
gsettings set org.mate.pluma display-right-margin true
gsettings set org.mate.pluma enable-search-highlighting true
gsettings set org.mate.pluma highlight-current-line true
gsettings set org.mate.pluma auto-indent true
gsettings set org.mate.pluma insert-spaces true
gsettings set org.mate.pluma active-plugins \
  "['trailsave', 'docinfo', 'time', 'spell', 'filebrowser', 'modelines']"

