#!/usr/bin/env fish
#
# Sets up my MATE desktop settings.

gsettings set org.mate.interface monospace-font-name "Ubuntu Mono 15"

# Mouse
#
# Low sensitivity so it's easy to make fine adjustments.
gsettings set org.mate.peripherals-mouse motion-threshold 3
# High acceleration so the mouse moves quickly to the other side of the screen.
gsettings set org.mate.peripherals-mouse motion-acceleration 10

# Touchpad
#
# TODO: Delete these lines if we decide we are happy with the defaults.
#
# gsettings set org.mate.peripherals-touchpad motion-threshold 3
# gsettings set org.mate.peripherals-touchpad motion-acceleration 6.5
gsettings set org.mate.peripherals-touchpad tap-to-click true
gsettings set org.mate.peripherals-touchpad vertical-two-finger-scrolling true
gsettings set org.mate.peripherals-touchpad horizontal-two-finger-scrolling true

# Keyboard
#
# Make CapsLock behave like another Escape key.
gsettings set org.mate.peripherals-keyboard-xkb.kbd options "['caps\tcaps:escape']"
# Enable Dvorak layout at the ibus level. This ensures that i3 sees the Dvorak
# keypresses.
gsettings set org.freedesktop.ibus.general engines-order "['xkb:us::eng', 'xkb:us:dvorak:eng']"
gsettings set org.freedesktop.ibus.general preload-engines "['xkb:us::eng', 'xkb:us:dvorak:eng']"
# Disable Dvorak at the MATE level to avoid confusion.
gsettings set org.mate.peripherals-keyboard-xkb.kbd layouts "['us']"

# Power management
gsettings set org.mate.power-manager idle-dim-battery false
gsettings set org.mate.power-manager idle-dim-ac false
gsettings set org.mate.power-manager backlight-battery-reduce false
# Don't lock the screen or suspend when the lid is closed on AC power. Usually
# I just have the laptop docked and I want to be able to close the lid to keep
# it out of my way.
gsettings set org.mate.power-manager button-lid-ac nothing

# Pluma (text editor)
gsettings set org.mate.pluma side-pane-visible true
gsettings set org.mate.pluma wrap-mode GTK_WRAP_WORD
gsettings set org.mate.pluma color-scheme cobalt
gsettings set org.mate.pluma use-default-font true
gsettings set org.mate.pluma auto-save false
gsettings set org.mate.pluma bracket-matching true
gsettings set org.mate.pluma display-line-numbers true
gsettings set org.mate.pluma tabs-size 2
gsettings set org.mate.pluma right-margin-position 80
gsettings set org.mate.pluma display-right-margin true
gsettings set org.mate.pluma enable-search-highlighting true
gsettings set org.mate.pluma highlight-current-line true
gsettings set org.mate.pluma auto-indent true
gsettings set org.mate.pluma insert-spaces true
gsettings set org.mate.pluma active-plugins \
  "['trailsave', 'docinfo', 'time', 'spell', 'filebrowser', 'modelines']"

