#!/bin/sh
#
# Flattens a directory hierarchy:
#
#   -A
#    +-B                     -A_B
#   -C        --becomes-->   -C_D
#    +-D                     -C_E_F
#    +-E
#      +-F
#
# Intended for processing CD track directories.

# Move files up to the top level.
find -type f -exec \
  dash -c \
  'echo -n "{}" | sed "s/^..//" | tr / _ | xargs --null --max-lines=1 mv "{}"' \; \
  || exit 1

# Now remove the leftover directories.
find -mindepth 1 -type d -delete \
  || exit 1
