#!/usr/bin/env fish
#
# Sometimes i3blocks terminates with exit status zero for a reason I don't
# understand (see https://github.com/vivien/i3blocks/issues/388). As a
# workaround, we call it in a loop here. On all but the first invocation, we
# suppress the first 2 lines (which start the infinite JSON list).

# TODO: remove logging
i3blocks -vv 2>~/log/i3blocks.stderr | tee ~/log.i3blocks.stdout
or exit

# i3blocks exited with status zero.
while true
  i3blocks | tail -n +2
  or exit
end
