#!/bin/sh
#
# Additional software needed for graphical desktops.

yes | sudo apt-get install \
  abcde audacity cdparanoia eyed3 feh fonts-dejavu ffmpeg gimp i3 i3blocks \
  kate kde-plasma-desktop keepassx kde-spectacle lame mate-desktop-environment \
  mate-desktop-environment-extras meld moc moc-ffmpeg-plugin muon numlockx \
  pdfsam scrot terminator vlc xbacklight xdotool \
  || exit 1

# Copy over my special mouse settings.
sudo cp \
  ~/sbp/sbp_linux_config/80-trackman.conf \
  ~/sbp/sbp_linux_config/81-elecom.conf \
  /usr/share/X11/xorg.conf.d \
  || exit 1
