#!/bin/sh

long_name=
for f in "${@}"; do
  # Remove the .mp3 suffix.
  f="$(basename "${f}" .mp3)"

  # Join the names into a long name.
  if [ ! -z "${long_name}" ]; then
    long_name="${long_name}__"
  fi
  long_name="${long_name}${f}"
done

if [ -z "${long_name}" ]; then
  echo "No inputs"
  exit 1
fi

echo "Building ${long_name}.mp3"
sox "${@}" "${long_name}.mp3"
