#!/usr/bin/env fish

set dirname (basename (pwd))
set files (find -name '*.mp3' | sort)

set counter 1
while test (count $files) -gt 0
  set outfile (printf '%s %02d-%02d.mp3' $dirname $counter (math $counter + 1))

  echo '~' Building $outfile from $files[1..2]
  echo '~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~'

  sox $files[1..2] $outfile
  or exit 1

  set files $files[3..-1]
  set counter (math $counter + 2)
end
