#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Library formatting numbers for use in i3bar status lines.

import re
import math
import string
import sys

# We use binary (not SI) prefixes.
PREFIX_FACTOR = 1024
PREFIXES = [' ', 'K', 'M', 'G', 'T', 'P', 'E', 'Z', 'Y']

LEFT_BAR  = u'▏'
RIGHT_BAR = u'▕'
VERTICAL_FILL   = u' ▁▂▃▄▅▆▇█'


def shortBytes(bytes, skip_prefixes=0):
  """ Pretty-prints a number of bytes. The result will never exceed 3
  characters in length. If 'skip_prefixes' is greater than zero, it gives
  the number of binary SI prefixes to skip over. Quantities smaller than
  these first non-skipped prefix will be rounded away.
  """
  bytes = float(bytes)
  
  prefix = skip_prefixes
  bytes /= PREFIX_FACTOR ** skip_prefixes
  
  if bytes < 999.5:
    # No need for prefixes.
    return '%3d' % round(bytes)
  
  while bytes >= 99.5:
    # The bytes won't fit into 2 characters, so move to a higher prefix.
    bytes /= PREFIX_FACTOR
    prefix += 1

  if bytes < 0.05:
    bytesStr = ' 0'
  elif bytes < 0.95:
    bytesStr = '.%d' % round(bytes * 10)
  elif bytes < 9.5:
    bytesStr = ' %d' % round(bytes)
  else:
    bytesStr = '%d' % round(bytes)

  if prefix == 0:
    return PREFIXES[prefix] + bytesStr
  else:
    return bytesStr + PREFIXES[prefix]
  
    
def roundToVerticalBar(fraction):
  """ Fetches the closest bar character for the given fraction. """
  # Prevent non-positive values.
  fraction = min(1, max(0.001, fraction))
  # We always want bar graphs to show at least a sliver along the bottom. So
  # we round up to the next fraction of 8.
  index = int(math.ceil(fraction * 8))
  return VERTICAL_FILL[index]

  
def stripNonDigits(text):
  """ Strips non-digit characters from the beginning and end of text. """
  begin = 0
  end = len(text) - 1
  while begin <= end and not text[begin].isdigit():
    begin += 1
  while begin <= end and not text[end].isdigit():
    end -= 1
  return text[begin:end+1]


# Pattern for matching percentages. Note the leading and trailing spaces.
percentagePattern = re.compile(r' *[0-9]+\% *')

def replacePercentageWithBar(text):
  """ Replaces the first occurrence of a percentage (like XXX%) in 'text'
  with a bar-graph that represents the same quantity.
  """
  m = re.search(percentagePattern, text)
  if m is None:
    return text
  percentageText = m.group(0)
  fraction = float(stripNonDigits(percentageText)) * 0.01
  barGraph = RIGHT_BAR + roundToVerticalBar(fraction) + LEFT_BAR
  return string.replace(text, percentageText, barGraph, 1)


if __name__ == '__main__':
  sys.stdout.write(
    replacePercentageWithBar(
      unicode(
        sys.stdin.read(),
        'utf-8')))
