#!/bin/sh
# Standard locking procedure. Instead of using the real i3lock, I use
# cinnamon-screensaver. Note that the screensaver instance is already running
# as a part of cinnamon-settings-daemon; this script just sends that instance
# a command.

cinnamon-screensaver-command --lock
