#!/bin/sh
#
# Suspend and lock screen.

# First issue a lock command so that when the system comes back the screen is
# still locked.
sbplock

# TODO: this still asks for a password :(
systemctl suspend
