#!/bin/sh
#
# Suspend and lock screen.

# First issue a lock command so that when the system comes back the screen is
# still locked.
sbplock

# TODO: this still asks for a password :(
# TODO: Maybe just get rid of this script (and its entry in the menu)? I only
# care about standby mode for my laptop, and closing the lid gets me that.
systemctl suspend
