#!/bin/sh
# Brings up a dmenu dialog, allowing the user to choose various shutdown
# options.

response=$(echo -e "shutdown\nrestart\nlogout\nlock" | sbp-dmenu -b)
case "$response" in
  shutdown)
    sbpshutdown ;;

  restart)
    sbprestart ;;

  logout)
    sbplogout ;;

  lock)
    sbplock ;;

  *)
    # User must have quit the dmenu. Do nothing.
    exit 1 ;;
esac
