#!/bin/sh
# Attach if a session exists; otherwise create a new session.

# I really only use tmux when SSHing. Use a common session name.
session='ssh'

tmux attach-session -t "$session" || tmux new-session -s "$session"
