#!/bin/sh
#
# Taken from
# http://superuser.com/questions/285381/how-does-the-tmux-color-palette-work
# These "colourXXX" codes can be used with tmux.

for i in {0..255} ; do
    printf "\x1b[38;5;${i}mcolour${i}\n"
done
