#!/usr/bin/env fish

set original (/usr/share/i3blocks/battery)

# The default (white) is shown when the battery is fully charged.
set color '#FFFFFF'
if string match '*DIS*' $original >/dev/null
  # Use yellow to indicate discharge.
  set color '#FFFF00'
else if string match '*CHR*' $original >/dev/null
  # Use blue to indicate charging.
  set color '#0077FF'
end

# Strip out DIS and CHR, since I use a color instead. Strip out parentheses
# since they add no meaning
printf "%s\n" $original | \
  sed 's/ DIS//' | \
  sed 's/ CHR//' | \
  tr --delete "()" | \
  sbp_main i3blocks_recolor --fg_color="$color"
