#!/bin/sh
#
# Suspend and lock screen. Unfortunately, this promps for a password, so we
# can't invoke it from an i3 keybinding. But I have kept the script in case I
# ever want to invoke it manually.

# First issue a lock command so that when the system comes back the screen is
# still locked.
sbplock

systemctl suspend
